/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaskelompok1;


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/** 
 *
 * @author user
 */

public class listTugas1 extends javax.swing.JFrame {
    /**
     * Creates new form listTugas
     */
    
    DefaultTableModel model;
    
    public listTugas1() {
        initComponents();
        
        model = (DefaultTableModel) tabel.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputdialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        buttonkeluar = new javax.swing.JButton();
        buttonok = new javax.swing.JButton();
        nomor_ = new javax.swing.JLabel();
        judul_ = new javax.swing.JLabel();
        update_ = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deadline_ = new javax.swing.JLabel();
        url_ = new javax.swing.JLabel();
        nomortf = new javax.swing.JTextField();
        judultf = new javax.swing.JTextField();
        urltf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        deskripsitf = new javax.swing.JTextArea();
        jDate = new com.toedter.calendar.JDateChooser();
        matkultf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateupdate = new com.toedter.calendar.JDateChooser();
        deadline_1 = new javax.swing.JLabel();
        waktudeadline = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        newbutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        hapusbutton = new javax.swing.JButton();
        lihatbutton = new javax.swing.JButton();
        kembalibutton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        inputdialog.setTitle("Masukkan Tugasmu Disini!");
        inputdialog.setBackground(new java.awt.Color(51, 51, 255));
        inputdialog.setMaximumSize(new java.awt.Dimension(1000, 1000));
        inputdialog.setMinimumSize(new java.awt.Dimension(450, 600));
        inputdialog.setPreferredSize(new java.awt.Dimension(450, 600));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(450, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(450, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 600));

        buttonkeluar.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        buttonkeluar.setText("KEMBALI");
        buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkeluarActionPerformed(evt);
            }
        });

        buttonok.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        buttonok.setText("OK");
        buttonok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonokActionPerformed(evt);
            }
        });

        nomor_.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        nomor_.setForeground(new java.awt.Color(255, 255, 255));
        nomor_.setText("Nomor");

        judul_.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        judul_.setForeground(new java.awt.Color(255, 255, 255));
        judul_.setText("Judul");

        update_.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        update_.setForeground(new java.awt.Color(255, 255, 255));
        update_.setText("Tanggal Update");

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Deskripsi");

        deadline_.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        deadline_.setForeground(new java.awt.Color(255, 255, 255));
        deadline_.setText("Tanggal Deadline");

        url_.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        url_.setForeground(new java.awt.Color(255, 255, 255));
        url_.setText("URL");

        nomortf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomortfActionPerformed(evt);
            }
        });

        urltf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urltfActionPerformed(evt);
            }
        });

        deskripsitf.setColumns(20);
        deskripsitf.setRows(5);
        jScrollPane2.setViewportView(deskripsitf);

        jDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDatePropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mata Kuliah");

        dateupdate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateupdatePropertyChange(evt);
            }
        });

        deadline_1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        deadline_1.setForeground(new java.awt.Color(255, 255, 255));
        deadline_1.setText("Waktu Deadline");

        waktudeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktudeadlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(buttonok, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(buttonkeluar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(url_)
                                    .addComponent(deadline_)
                                    .addComponent(deadline_1)
                                    .addComponent(jLabel2)
                                    .addComponent(update_)
                                    .addComponent(judul_)
                                    .addComponent(nomor_))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addComponent(waktudeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                                    .addComponent(matkultf))
                                                .addComponent(dateupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(judultf, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(urltf, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nomortf, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomor_)
                    .addComponent(nomortf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judul_)
                    .addComponent(judultf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(update_))
                    .addComponent(dateupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(matkultf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadline_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadline_1)
                    .addComponent(waktudeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(url_))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout inputdialogLayout = new javax.swing.GroupLayout(inputdialog.getContentPane());
        inputdialog.getContentPane().setLayout(inputdialogLayout);
        inputdialogLayout.setHorizontalGroup(
            inputdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        inputdialogLayout.setVerticalGroup(
            inputdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabel.setBackground(new java.awt.Color(204, 204, 204));
        tabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor", "Judul", "Tgl Update", "Mata Kuliah", "Deskripsi", "Tgl Deadline", "Waktu Deadline", "URL", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        tabel.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tabelInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setHeaderValue("Nomor");
            tabel.getColumnModel().getColumn(1).setHeaderValue("Judul");
            tabel.getColumnModel().getColumn(2).setHeaderValue("Tgl Update");
            tabel.getColumnModel().getColumn(3).setHeaderValue("Mata Kuliah");
            tabel.getColumnModel().getColumn(4).setHeaderValue("Deskripsi");
            tabel.getColumnModel().getColumn(5).setHeaderValue("Tgl Deadline");
            tabel.getColumnModel().getColumn(6).setHeaderValue("Waktu Deadline");
            tabel.getColumnModel().getColumn(7).setHeaderValue("URL");
            tabel.getColumnModel().getColumn(8).setHeaderValue("Status");
        }

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TO DO LIST");

        newbutton.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        newbutton.setText("+");
        newbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbuttonActionPerformed(evt);
            }
        });

        editbutton.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        editbutton.setText("Edit");
        editbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbuttonMouseClicked(evt);
            }
        });
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        hapusbutton.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        hapusbutton.setText("Hapus");
        hapusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbuttonActionPerformed(evt);
            }
        });

        lihatbutton.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        lihatbutton.setText("Lihat");
        lihatbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lihatbuttonMouseClicked(evt);
            }
        });
        lihatbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatbuttonActionPerformed(evt);
            }
        });

        kembalibutton.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        kembalibutton.setText("Kembali");
        kembalibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalibuttonActionPerformed(evt);
            }
        });

        output.setColumns(20);
        output.setRows(5);
        jScrollPane3.setViewportView(output);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(newbutton)
                        .addGap(37, 37, 37)
                        .addComponent(editbutton)
                        .addGap(36, 36, 36)
                        .addComponent(hapusbutton)
                        .addGap(33, 33, 33)
                        .addComponent(lihatbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kembalibutton)
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newbutton)
                    .addComponent(editbutton)
                    .addComponent(hapusbutton)
                    .addComponent(lihatbutton)
                    .addComponent(kembalibutton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDatePropertyChange
        // TODO add your handling code here:
        date();
    }//GEN-LAST:event_jDatePropertyChange

    String update;
    public void date(){
        if(dateupdate.getDate() != null){
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(pattern);
        update = String.valueOf(format.format(dateupdate.getDate()));
        }
    }
    
    private void buttonokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonokActionPerformed
    // TODO add your handling code here:
        model.addRow(new Object[]{nomortf.getText(), judultf.getText(), dateupdate.getDate(), matkultf.getText(), deskripsitf.getText(), jDate.getDate(), waktudeadline.getText(),urltf.getText(), false});
        inputdialog.dispose();
    }//GEN-LAST:event_buttonokActionPerformed

    private void buttonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkeluarActionPerformed
        // TODO add your handling code here:
        inputdialog.dispose();
    }//GEN-LAST:event_buttonkeluarActionPerformed

    private void newbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbuttonActionPerformed
        // TODO add your handling code here:
        inputdialog.setVisible(true);
        nomortf.setText("");
        judultf.setText("");
        dateupdate.setDate(null);
        matkultf.setText("");
        deskripsitf.setText("");
        jDate.setDate(null);
        waktudeadline.setText("");
        urltf.setText("");
        
    }//GEN-LAST:event_newbuttonActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        // TODO add your handling code here:
        if(tabel.getSelectedRow() != -1)
            edit();
    }//GEN-LAST:event_editbuttonActionPerformed

    void edit() {
    inputdialog.setVisible(true);
    nomortf.setText(model.getValueAt(tabel.getSelectedRow(),0).toString());
    judultf.setText(model.getValueAt(tabel.getSelectedRow(),1).toString());
    matkultf.setText(model.getValueAt(tabel.getSelectedRow(),3).toString());
    deskripsitf.setText(model.getValueAt(tabel.getSelectedRow(),4).toString());
    
        
}
            
    private void hapusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbuttonActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "apakah anda yakin ingin menghapus?", "konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if(input == 0 && tabel.getSelectedRow() != -1) {
            model.removeRow(tabel.getSelectedRow());
        } 
    }//GEN-LAST:event_hapusbuttonActionPerformed

    private void kembalibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalibuttonActionPerformed
        // TODO add your handling code here:
        TampilanAwal ta = new TampilanAwal();
        ta.setLocationRelativeTo(null);
        ta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembalibuttonActionPerformed

    private void editbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editbuttonMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2)
            edit();
    }//GEN-LAST:event_tabelMouseClicked

    private void lihatbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatbuttonActionPerformed
        // TODO add your handling code here:
        output.setText("Judul                = " + judultf.getText()
                + "\nUpdated            = " + dateupdate.getDate()
                + "\nMata Kuliah        = " + matkultf.getText()
                + "\nDeskripsi          = " + deskripsitf.getText()
                + "\nTanggal Deadline   = " + jDate.getDate()
                + "\nWaktu Deadline     = " + waktudeadline.getText()
                + "\nURL                = " + urltf.getText()
        ); 
    }//GEN-LAST:event_lihatbuttonActionPerformed

    private void lihatbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatbuttonMouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_lihatbuttonMouseClicked

    private void dateupdatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateupdatePropertyChange
        // TODO add your handling code here:
        tanggal();
    }//GEN-LAST:event_dateupdatePropertyChange

    private void nomortfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomortfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomortfActionPerformed

    private void waktudeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktudeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktudeadlineActionPerformed

    private void urltfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urltfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urltfActionPerformed

    private void tabelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tabelInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    String deadline;
    public void tanggal(){
        if(jDate.getDate() != null){
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(pattern);
        deadline = String.valueOf(format.format(jDate.getDate()));
        }
    }
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listTugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JButton buttonok;
    private com.toedter.calendar.JDateChooser dateupdate;
    private javax.swing.JLabel deadline_;
    private javax.swing.JLabel deadline_1;
    private javax.swing.JTextArea deskripsitf;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton hapusbutton;
    private javax.swing.JDialog inputdialog;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel judul_;
    private javax.swing.JTextField judultf;
    private javax.swing.JButton kembalibutton;
    private javax.swing.JButton lihatbutton;
    private javax.swing.JTextField matkultf;
    private javax.swing.JButton newbutton;
    private javax.swing.JLabel nomor_;
    private javax.swing.JTextField nomortf;
    private javax.swing.JTextArea output;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel update_;
    private javax.swing.JLabel url_;
    private javax.swing.JTextField urltf;
    private javax.swing.JTextField waktudeadline;
    // End of variables declaration//GEN-END:variables

    private void simpan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    

    

    
}
